name: Build with makepkg

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Package
      run: |
        docker pull archlinux:latest
        docker run --rm -v $(pwd):/pkg -w /pkg archlinux:latest bash -c "pacman -Sy --noconfirm base-devel fuse2 && useradd -u $(id -u) runner && su runner -s /bin/sh -c 'makepkg -sf && makepkg --printsrcinfo > .SRCINFO'"

    - name: Configure Git
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/aur
        chmod 600 ~/.ssh/aur
        git config --global --add safe.directory $(pwd)
        git config --global user.email "mr@deltachaos.de"
        git config --global user.name "Maximilian Ruta"
        git remote add aur ssh://aur@aur.archlinux.org/raiderio-client-appimage.git 

    - name: Create commit
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected"
          git add .
          git commit -m "Update from CI"
        else
          echo "No changes detected"
          exit 0
        fi
        
    - name: Push changes
      run: |
        GIT_SSH_COMMAND="ssh -i ~/.ssh/aur -o StrictHostKeyChecking=accept-new" git push aur master
        git push origin master
